// src/attributes.js
export const attributes = {
  Weirdness: [
    "Acquired Taste",
    "Blood Thirst",
    "Dumb Luck",
    "Imaginary Friend",
    "The Insanity Defense",
    "Knickknack Paddywhack",
    "Lucky Break",
    "Modification*",
    "Mutation*",
    "Trash Picking",
  ],
  Agility: [
    "Acrobatics",
    "Action!*",
    "All in the Wrist",
    "Gunslinging",
    "Kill Streak",
    "Pep in Your Step",
    "Stealth",
    "Sticky Fingers",
    "Sudden Reversal",
    "Wall Crawling",
  ],
  Strength: [
    "Athletics",
    "Beatdown",
    "Follow-Through",
    "Fists of Legend*",
    "Holding Back",
    "Knockout Blow",
    "The Old Heave-Ho",
    "Overpacking",
    "Unstoppable Force",
    "Viselike Grip",
  ],
  Toughness: [
    "Fast Metabolism",
    "Grit*",
    "Immovable Object",
    "Nine Lives",
    "Restlessness",
    "Roughing It",
    "Running Interference",
    "Second Wind",
    "Thick Skin",
    "Tough Break",
  ],
  Observation: [
    "Bullseye",
    "Cold Reading",
    "Friendlier Fire",
    "Hypervigilance",
    "Infiltration",
    "Keen Senses",
    "Sharpshooting",
    "Sizing Up",
    "Tracking",
    "Treasure Hunting",
  ],
  Intelligence: [
    "Chemistry",
    "Demolitions",
    "Diverse Interests*",
    "Emergency Care",
    "Expertise*",
    "Foresight",
    "Hacking",
    "Jury Rigging",
    "Laser Focus",
    "Life Lessons",
  ],
  Demeanor: [
    "Arresting Gaze",
    "Authority",
    "Bartering",
    "Beast Mastery",
    "Disguise",
    "Fair Warning",
    "Honest Face",
    "Leadership",
    "The Nod",
    "Pet*",
  ],
};
