export const items = [
"Ammo ×3 (tiny)",
"Canteen (3 drinks)",
"Cure-all ×3 (tiny)",
"Battery",
"Bear trap",
"Binoculars",
"Flashlight",
"Food ×3",
"Geiger counter",
"Lantern",
"Junk ×3",
"Oil canister",
"Poison ×3 (tiny)",
"Flares ×6 (tiny)",
"Rope",
"Stim ×3 (tiny)",
"Tent (big)",
"Tool belt",
"Trank ×3 (tiny)",
"Wrist terminal",
]
