export const outfits = [
  "Bathrobe",
  "Bomber jacket",
  "Duct-taped parka",
  "Flannel & jeans",
  "Floral party wear",
  "Hospital gown",
  "Knitted sweater",
  "Lab coat",
  "Letter jacket",
  "Lightweight jumpsuit",
  "Mechanic's coverall",
  "Military fatigues",
  "Nylon track suit",
  "Overalls & gloves",
  "Prison coverall",
  "Rags",
  "Rumpled suit & tie",
  "Surgical scrubs",
  "T-shirt & jeans",
  "Biker leathers (4 AP)",
];
