export const quirks = [
  "Always chewing a toothpick",
  "Attracts stray cats",
  "Avoiding a cult (it's a long story)",
  "Big hole clean through left palm",
  "Blackest eye makeup (no—blacker)",
  "Calls people “Boss” or “Chuckles”",
  "Circuitry-shaped scars over body",
  "Descendant of the last US president",
  "Held together by duct tape & spite",
  "Idly hums & beat-boxes",
  "Inexplicably invisible to most robots",
  "“It's my birthday,” you often say",
  "Known by trogs as “Cakebringer”",
  "Makes up slang, never explains it",
  "Oft mistaken for a notorious killer",
  "Periodically struck by lightning",
  "Perpetually impeccable haircut",
  "Pretty sure you're a clone",
  "Pre-war soda pop aficionado",
  "Quite possibly an intelligent chimp",
  "Railroad spike lodged in head",
  "Raised by trogs, robots, or crab-folk",
  "Says “pididdle” at wrecked cars",
  "Second face with mind of its own",
  "Sharp, biting, serrated sarcasm",
  "Significant gaps in memory",
  "Spitting image of a pre-war actor",
  "Strongly resembles a big lab rat",
  "Talks like a 1950s TV character",
  "Talks like everything's a question?",
  "Tells knock-knock jokes in combat",
  '"That\'s that freak who ate a robot"',
  "Truly god-awful puns",
  "Very slightly magnetized",
  "Woken from pre-war cryo chamber",
  "You have your father's eyes",
];
