export const trinkets = [
  "Bowler hat (worn jauntily)",
  "Bus token (service is delayed)",
  "Denver snow globe",
  "Cowboy hat",
  "Cracked eyeglasses",
  "Dog tags",
  "Eerily accurate mood ring",
  "Elastic band you can shoot far",
  "Fake mustache & glasses",
  "Hair spray, still some left",
  "Hearing aid (picks up radio)",
  "Joy buzzer",
  "Knitting needles & yarn",
  "Light-up sneakers",
  "Locket (t-rex photo inside)",
  "Luchador mask",
  "Lucky pickle (in jar)",
  "Metal lighter with cartoon devil",
  "Paddleball (extra-bouncy)",
  "Photo of someone frowning",
  "Pocketful of paperclips",
  "Poker deck (missing Ace of ♥)",
  "Polka-dotted handkerchief",
  "Pre-war action figure",
  "Pre-war wristwatch TV (busted)",
  "Sash full of merit badges",
  "School sports mascot mask",
  "Sexy eyepatch",
  "Silver dollar (some gum on it)",
  "Sparkly sticker collection",
  "Talking doll (gives bad advice)",
  "Trick dice",
  "3-D glasses",
  "Video cassette",
  "Wax pear",
  "Yo-yo (can do a few tricks)",
];
