export const weapons = [
"Crowbar (d6, awkward)",
"Lead pipe (d6, awkward)",
"Tire iron (d6, awkward)",
"5-iron (d8, big, awkward)",
"Shovel (d8, big, awkward)",
"Baton (d6)",
"Brass knuckles (d6)",
"Dagger (d6)",
"Machete (d6)",
"Baseball bat (d8, big)",
"Fire axe (d8, big)",
"Sledgehammer (d8, big)",
"Stunner (d4, up-close)",
"Semiauto pistol (d6)",
"Revolver (d6)",
"Sawed-off (d8, up-close)",
"Hunting shotgun (d8, big)",
"Hunting rifle (d8, big)",
"Grenade ×3 (2d6, area)",
"Machine pistol (d6, auto)",
]
